# Generated by Django 4.1.2 on 2022-10-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_author_alter_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
