# Generated by Django 4.1.2 on 2022-10-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_question_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default='Admin', max_length=200),
        ),
    ]
