# Generated by Django 4.1.2 on 2022-10-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
